name: merc

services:
  api:
    container_name: merc-api
    build:
      context: .
      dockerfile: merc-api/Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin