name: merc

services:
  api:
    container_name: merc-api
    build:
      context: .
      dockerfile: merc-api/Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  worker:
    container_name: merc-worker
    build:
      context: .
      dockerfile: merc-worker/Dockerfile
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy